name: Data Load - New Data Resource Form
description: Create an issue to load a new data resource into the Atlas of Living Australia.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["AtlasOfLivingAustralia/21"]
body:
  - type: input
    id: dataResourceUid_prod
    attributes:
      label: Data Resource Uid in PROD
      placeholder: dr000 if N/A
    validations:
      required: false
  - type: input
    id: dataResourceUid_test
    attributes:
      label: Data Resource Uid in TEST
      placeholder: dr000 if N/A
    validations:
      required: false
  - type: checkboxes
    id: metadata
    attributes:
      label: Meta-data about the data resource
      options:
        - label: " Ask data provider for metadata, including:
            - Data resource name
            - Description
            - License: prefer Creative Commons Attribution https://creativecommons.org/licenses/by/4.0/
            - Citation: Statement to be used by those downloading and using these records
            - Contact: Email and/or phone number
            - Other fields as necessary"
          required: false
        - label: Using the metadata, create a new data resource using https://collections.ala.org.au/admin
          required: false
        - label: Ensure the correct connection parameters are specified at https://collections.ala.org.au/dataResource/show/drNNNN (Unique identifiers! Protocol!)
          required: false
        
  - type: checkboxes
    id: dataPrep
    attributes:
      label: Data Preparation Steps
      options:
        - label: Map dataset to Darwin Core Terms in a CSV if necessary http://rs.tdwg.org/dwc/terms/. Package the CSV into a Darwin Core Archive
          required: false
        - label: Ensure the dataset has correctly specified unique identifier without duplicates
          required: false
        - label: Ensure images are specified in an images file in the DwCA with the identifier field populated
          required: false
        - label: Check that species, location, times are adequately specific. Check back with the data provider if necessary
          required: false
